# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff2138b2c840150f724c012fa3a06247154514255feb6fc710752dfcbd99d7e4d9ce4174c2b554963c283bd65da9a6bcf8ec0baa9b751f48886ed4c9b7137f3

test:
  secret_key_base: 5ac380c9e7f1d4c1045fa1f87e8432f9dc72052196f75d3c04a1c18093efb1029a165f8a1c84a4b1aa47034a695c27266a1f7ecce00c9386e3c41fea286be619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
